services:
  postgres:
    image: postgres:18
    container_name: instagram_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: insta_db

    ports:
      - "5433:5432"

    volumes:
      - instagram_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d insta_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: instagram-app:latest
    container_name: instagram_app

    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/insta_db

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  instagram_postgres_data: